### ISSUE TITLE
How should I handle more schemes?

### ISSUE THREAD

**Issue by tivadarmolitorisz** [freelancer/ios-modular-architecture#1]
Hi Guys (@CyrilCermak, @joshuadeguzman)

I've just read the article and it's so cool :).
I have a problem because I wanted to try the sample project out with some different schemes (like Debug UAT, Debug SIT, Debug Production, etc) but it seems for me it's not supported in this case.
Do you have any idea how I should achieve this?
Actually, I would have the main app project with some schemes and some feature modules with only debug/release scheme.  

Thank you.

**Comment by CyrilCermak** [comment]
Hey Tivadar György, first of all, thank you very much for your response. Yes I think you are right, since each framework has it's own configuration and is being linked towards your main App you probably won't be able to set module schemes separately. Actually, I did not play around with that much, but have you tried to add the same configuration to each framework? Maybe xcode will figure it out. It could work the same as Debug and Release in that case. So lets say you will add QA configuration to your main App and then to each framework that you are developing alongside of that, xcode could then pick the configuration based on the main App target. I will try it as soon as I have some spare time. :) 

Thank you Cyril.

**Comment by CyrilCermak** [comment]
So it works like I assumed. I created the same configuration(QA) for each framework and App target. Xcode then ran the the configuration I chose for the main App within linked frameworks as well. I also had to edit my Podfile a bit. With that being said I would say that schemas are fully supported in this architectural setup. :) 

Here is a working example so you can have a look.
[ios-modular-architecture-with-schema.zip](https://github.com/freelancer/ios-modular-architecture/files/3120589/ios-modular-architecture-with-schema.zip)

**Comment by tivadarmolitorisz** [comment]
Thanks @CyrilCermak, yeah it's working :). 

Best,
Tivadar
